version: "3"

services:
  back:
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: blog-back

  front:
    build: ./front
    ports:
      - "3000:3000"
    container_name: blog-front

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: blog-db